const KEYS={entradas:"lf_v35_entradas",despesas:"lf_v35_despesas",contas:"lf_v35_contas",auditoria:"lf_v35_auditoria",config:"lf_v35_config",fechamentos:"lf_v35_fechamentos"};
let config=load(KEYS.config,{empresa:"Lavanderia Fátima",telefone:"(21) 2232-6565",endereco:"Av. Nossa Sra. de Fátima, 50 - Centro, Rio de Janeiro - RJ",socias:["Sócia 1","Sócia 2","Sócia 3"],senha:"fatima2026"});
let entradas=load(KEYS.entradas,[]),despesas=load(KEYS.despesas,[]),contas=load(KEYS.contas,[]),auditoria=load(KEYS.auditoria,[]),fechamentos=load(KEYS.fechamentos,{}),currentUser=config.socias[0],editEntradaId=null,editDespesaId=null;
function load(k,def){try{return JSON.parse(localStorage.getItem(k))??def}catch(e){return def}} function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function money(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})} function parseMoney(v){let d=String(v||"").replace(/\D/g,"");return d?Number(d)/100:0} function setMoney(el,val){el.value=Number(val||0)?money(val):""} function today(){return new Date().toISOString().slice(0,10)} function month(){return today().slice(0,7)} function brDate(iso){if(!iso)return"-";let[y,m,d]=iso.split("-");return`${d}/${m}/${y}`} function activeRows(list){return list.filter(x=>!x.cancelado)} function sum(list){return list.reduce((s,x)=>s+Number(x.valor||0),0)} function audit(acao,detalhes,antes=null,depois=null){auditoria.unshift({data:new Date().toLocaleString("pt-BR"),usuario:currentUser,acao,detalhes,antes,depois});save(KEYS.auditoria,auditoria);renderHistorico()} function escapeHTML(s){return String(s??"").replace(/[&<>'"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[m]))} function isADM(){return currentUser==="ADM"} function closed(date){return !!fechamentos[date]}
document.addEventListener("DOMContentLoaded",()=>{bindLogin();bindNavigation();bindActions();setupInitialValues();renderAll()});
function bindLogin(){btnLogin.onclick=entrar;loginSenha.addEventListener("keydown",e=>{if(e.key==="Enter")entrar()});btnSair.onclick=sair;btnTrocarUsuario.onclick=abrirTrocaUsuario;btnConfirmarTroca.onclick=confirmarTrocaUsuario;btnCancelarTroca.onclick=()=>trocarUsuarioModal.classList.add("hidden")}
function entrar(){const senha=loginSenha.value.trim(),erro=loginErro;if(senha==="uzumaki"){currentUser="ADM"}else{if(senha!==config.senha){erro.textContent="Senha incorreta. Use a senha correta para entrar.";erro.classList.remove("hidden");loginSenha.value="";return}const radio=document.querySelector("input[name='perfilLogin']:checked");currentUser=radio?radio.value:config.socias[0]}usuarioAtual.textContent=currentUser;erro.classList.add("hidden");loginSenha.value="";loginScreen.classList.add("hidden");app.classList.remove("hidden");fillUserSelects();audit("Entrou no ERP",`Login realizado como ${currentUser}`);renderAll()}
function sair(){app.classList.add("hidden");loginScreen.classList.remove("hidden");loginSenha.focus()}
function abrirTrocaUsuario(){document.querySelectorAll("input[name='perfilTroca']").forEach(r=>r.checked=r.value===(isADM()?config.socias[0]:currentUser));trocarSenha.value="";trocarUsuarioModal.classList.remove("hidden")}
function confirmarTrocaUsuario(){const senha=trocarSenha.value.trim();let novo="";if(senha==="uzumaki"){novo="ADM"}else{if(senha!==config.senha){alert("Senha incorreta.");return}const radio=document.querySelector("input[name='perfilTroca']:checked");novo=radio?radio.value:currentUser}if(novo!==currentUser){const antigo=currentUser;currentUser=novo;usuarioAtual.textContent=currentUser;fillUserSelects();audit("Trocou usuário",`Usuário anterior: ${antigo}. Usuário atual: ${currentUser}`)}trocarUsuarioModal.classList.add("hidden")}
function bindNavigation(){document.querySelectorAll(".menu-btn").forEach(btn=>btn.onclick=()=>showScreen(btn.dataset.screen));document.querySelectorAll("[data-open]").forEach(btn=>btn.onclick=()=>showScreen(btn.dataset.open))}
function showScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".menu-btn").forEach(b=>b.classList.toggle("active",b.dataset.screen===id));const titles={dashboard:["Dashboard","Visão rápida da saúde financeira da loja."],entradas:["Entradas","Cadastre e edite recebimentos."],despesas:["Despesas","Controle gastos e contas."],notas:["Notas Carioca","Controle notas pendentes e duplicadas."],contas:["Contas a pagar","Alertas de vencimento."],fechamento:["Fechamento diário","Resumo e bloqueio do dia."],relatorios:["Relatórios","Filtros e exportações."],historico:["Histórico","Auditoria do sistema."],backup:["Backup","Exportar/importar dados."],config:["Configurações","Ajustes do sistema."]};pageTitle.textContent=titles[id][0];pageSubtitle.textContent=titles[id][1];if(id==="fechamento")renderFechamento();if(id==="relatorios")gerarRelatorio();window.scrollTo({top:0,behavior:"smooth"})}
function bindActions(){btnSalvarEntrada.onclick=salvarEntrada;btnCancelarEdicaoEntrada.onclick=cancelarEdicaoEntrada;btnSalvarDespesa.onclick=salvarDespesa;btnCancelarEdicaoDespesa.onclick=cancelarEdicaoDespesa;btnSalvarConta.onclick=salvarConta;btnAtualizarFechamento.onclick=renderFechamento;btnFecharDia.onclick=fecharDia;btnGerarRelatorio.onclick=gerarRelatorio;btnImprimir.onclick=()=>window.print();btnExportarEntradas.onclick=()=>exportCSV("entradas");btnExportarDespesas.onclick=()=>exportCSV("despesas");btnBackup.onclick=baixarBackup;btnBackupDash.onclick=baixarBackup;inputBackup.onchange=importarBackup;btnLimpar.onclick=limparDados;btnSalvarConfig.onclick=salvarConfig;[filtroEntradaBusca,filtroEntradaMes,filtroEntradaStatus].forEach(el=>el.oninput=renderEntradas);[filtroDespesaBusca,filtroDespesaMes,filtroDespesaStatus].forEach(el=>el.oninput=renderDespesas);[filtroNotasBusca,filtroNotasStatus].forEach(el=>el.oninput=renderNotas);document.querySelectorAll(".money").forEach(el=>el.addEventListener("input",()=>{const d=String(el.value).replace(/\D/g,"");el.value=d?money(Number(d)/100):""}))}
function setupInitialValues(){["entradaData","despesaData","fechamentoData","relInicio","relFim"].forEach(id=>document.getElementById(id).value=today());filtroEntradaMes.value=month();filtroDespesaMes.value=month();fillUserSelects();fillConfig()}
function fillUserSelects(){["entradaUsuario","despesaUsuario","fechamentoUsuario","contaUsuario","relUsuario"].forEach(id=>{const el=document.getElementById(id);let first=id==="relUsuario"?'<option value="">Todos usuários</option>':"";let lista=[...config.socias];if(isADM())lista.push("ADM");el.innerHTML=first+lista.map(s=>`<option>${escapeHTML(s)}</option>`).join("");if(id!=="relUsuario")el.value=currentUser})}
function notaDuplicada(numero,idIgnorar=null){return activeRows(entradas).some(e=>String(e.numeroNota).trim()===String(numero).trim()&&e.id!==idIgnorar)}
function salvarEntrada(){const data=entradaData.value,usuario=entradaUsuario.value,cliente=entradaCliente.value.trim(),valor=parseMoney(entradaValor.value),pagamento=entradaPagamento.value,numeroNota=entradaNumeroNota.value.trim(),erro=entradaErro;let faltas=[];if(!data)faltas.push("Data");if(!usuario)faltas.push("Lançado por");if(!cliente)faltas.push("Cliente");if(!valor)faltas.push("Valor");if(!pagamento)faltas.push("Forma de pagamento");if(!numeroNota)faltas.push("Nº da Nota");if(faltas.length){erro.innerHTML="<b>Preencha:</b><br>• "+faltas.join("<br>• ");erro.classList.remove("hidden");return}if(notaDuplicada(numeroNota,editEntradaId)){erro.innerHTML="<b>Nº da Nota já usado.</b><br>Confira se essa nota já foi lançada.";erro.classList.remove("hidden");return}if(editEntradaId&&(!entradaMotivo.value.trim())){erro.innerHTML="<b>Informe o motivo da edição.</b>";erro.classList.remove("hidden");return}erro.classList.add("hidden");const item={id:editEntradaId||Date.now(),data,usuario,cliente,cpf:entradaCpf.value.trim(),valor,pagamento,nota:entradaNota.value,numeroNota,descricao:entradaDescricao.value.trim(),cancelado:false};if(editEntradaId){let i=entradas.findIndex(e=>e.id===editEntradaId),antes={...entradas[i]};entradas[i]={...entradas[i],...item};audit("Editou entrada",`${cliente} - ${money(valor)}. Motivo: ${entradaMotivo.value.trim()}`,antes,entradas[i]);cancelarEdicaoEntrada(false)}else{entradas.push(item);audit("Criou entrada",`${cliente} - ${money(valor)} - Nota ${numeroNota}`)}save(KEYS.entradas,entradas);limparEntrada();renderAll();alert("Entrada salva.")}
function editarEntrada(id){const e=entradas.find(x=>x.id===id);if(!e)return;editEntradaId=id;entradaTitulo.textContent="Editar Entrada";btnSalvarEntrada.textContent="Atualizar Entrada";btnCancelarEdicaoEntrada.classList.remove("hidden");entradaMotivoBox.classList.remove("hidden");entradaMotivo.value="";entradaData.value=e.data;entradaUsuario.value=e.usuario;entradaCliente.value=e.cliente;entradaCpf.value=e.cpf||"";setMoney(entradaValor,e.valor);entradaPagamento.value=e.pagamento;entradaNota.value=e.nota;entradaNumeroNota.value=e.numeroNota;entradaDescricao.value=e.descricao||"";showScreen("entradas")}
function cancelarEntrada(id){const e=entradas.find(x=>x.id===id);if(!e)return;const motivo=prompt("Motivo do cancelamento:");if(!motivo)return;const antes={...e};e.cancelado=true;e.motivoCancelamento=motivo;e.canceladoPor=currentUser;e.canceladoEm=new Date().toLocaleString("pt-BR");save(KEYS.entradas,entradas);audit("Cancelou entrada",`${e.cliente} - ${money(e.valor)}. Motivo: ${motivo}`,antes,e);renderAll()}
function cancelarEdicaoEntrada(clear=true){editEntradaId=null;entradaTitulo.textContent="Registrar Entrada";btnSalvarEntrada.textContent="Salvar Entrada";btnCancelarEdicaoEntrada.classList.add("hidden");entradaMotivoBox.classList.add("hidden");if(clear)limparEntrada()}
function limparEntrada(){["entradaCliente","entradaCpf","entradaValor","entradaNumeroNota","entradaDescricao","entradaMotivo"].forEach(id=>document.getElementById(id).value="");entradaPagamento.value="";entradaNota.value="Pendente";entradaData.value=today();entradaUsuario.value=currentUser}
function salvarDespesa(){const data=despesaData.value,usuario=despesaUsuario.value,categoria=despesaCategoria.value,valor=parseMoney(despesaValor.value),status=despesaStatus.value,descricao=despesaDescricao.value.trim(),erro=despesaErro;let faltas=[];if(!data)faltas.push("Data");if(!usuario)faltas.push("Lançado por");if(!categoria)faltas.push("Categoria");if(!valor)faltas.push("Valor");if(!status)faltas.push("Status");if(!descricao)faltas.push("Descrição");if(faltas.length){erro.innerHTML="<b>Preencha:</b><br>• "+faltas.join("<br>• ");erro.classList.remove("hidden");return}if(editDespesaId&&(!despesaMotivo.value.trim())){erro.innerHTML="<b>Informe o motivo da edição.</b>";erro.classList.remove("hidden");return}erro.classList.add("hidden");const item={id:editDespesaId||Date.now(),data,usuario,categoria,valor,status,descricao,vencimento:despesaVencimento.value,cancelado:false};if(editDespesaId){let i=despesas.findIndex(d=>d.id===editDespesaId),antes={...despesas[i]};despesas[i]={...despesas[i],...item};audit("Editou despesa",`${categoria} - ${money(valor)}. Motivo: ${despesaMotivo.value.trim()}`,antes,despesas[i]);cancelarEdicaoDespesa(false)}else{despesas.push(item);audit("Criou despesa",`${categoria} - ${money(valor)}`)}save(KEYS.despesas,despesas);limparDespesa();renderAll();alert("Despesa salva.")}
function editarDespesa(id){const d=despesas.find(x=>x.id===id);if(!d)return;editDespesaId=id;despesaTitulo.textContent="Editar Despesa";btnSalvarDespesa.textContent="Atualizar Despesa";btnCancelarEdicaoDespesa.classList.remove("hidden");despesaMotivoBox.classList.remove("hidden");despesaMotivo.value="";despesaData.value=d.data;despesaUsuario.value=d.usuario;despesaCategoria.value=d.categoria;setMoney(despesaValor,d.valor);despesaStatus.value=d.status;despesaVencimento.value=d.vencimento||"";despesaDescricao.value=d.descricao;showScreen("despesas")}
function cancelarDespesa(id){const d=despesas.find(x=>x.id===id);if(!d)return;const motivo=prompt("Motivo do cancelamento:");if(!motivo)return;const antes={...d};d.cancelado=true;d.motivoCancelamento=motivo;d.canceladoPor=currentUser;d.canceladoEm=new Date().toLocaleString("pt-BR");save(KEYS.despesas,despesas);audit("Cancelou despesa",`${d.categoria} - ${money(d.valor)}. Motivo: ${motivo}`,antes,d);renderAll()}
function cancelarEdicaoDespesa(clear=true){editDespesaId=null;despesaTitulo.textContent="Registrar Despesa";btnSalvarDespesa.textContent="Salvar Despesa";btnCancelarEdicaoDespesa.classList.add("hidden");despesaMotivoBox.classList.add("hidden");if(clear)limparDespesa()}
function limparDespesa(){["despesaValor","despesaDescricao","despesaVencimento","despesaMotivo"].forEach(id=>document.getElementById(id).value="");despesaCategoria.value="";despesaStatus.value="Pago";despesaData.value=today();despesaUsuario.value=currentUser}
function salvarConta(){let valor=parseMoney(contaValor.value),faltas=[];if(!contaFornecedor.value.trim())faltas.push("Fornecedor");if(!contaCategoria.value)faltas.push("Categoria");if(!valor)faltas.push("Valor");if(!contaVencimento.value)faltas.push("Vencimento");if(faltas.length){contaErro.innerHTML="<b>Preencha:</b><br>• "+faltas.join("<br>• ");contaErro.classList.remove("hidden");return}contaErro.classList.add("hidden");contas.push({id:Date.now(),fornecedor:contaFornecedor.value.trim(),categoria:contaCategoria.value,valor,vencimento:contaVencimento.value,status:contaStatus.value,usuario:contaUsuario.value,obs:contaObs.value.trim(),cancelado:false});save(KEYS.contas,contas);audit("Criou conta a pagar",`${contaFornecedor.value} - ${money(valor)} - vence ${brDate(contaVencimento.value)}`);["contaFornecedor","contaValor","contaVencimento","contaObs"].forEach(id=>document.getElementById(id).value="");contaCategoria.value="";contaStatus.value="Pendente";renderAll();alert("Conta salva.")}
function marcarContaPaga(id){let c=contas.find(x=>x.id===id);if(!c)return;c.status="Pago";save(KEYS.contas,contas);audit("Marcou conta como paga",`${c.fornecedor} - ${money(c.valor)}`);renderAll()}
function renderAll(){renderDashboard();renderEntradas();renderDespesas();renderNotas();renderContas();renderHistorico();renderFechamento();gerarRelatorio()}
function renderDashboard(){const h=today(),m=h.slice(0,7),eHoje=activeRows(entradas).filter(e=>e.data===h),dHoje=activeRows(despesas).filter(d=>d.data===h),eMes=activeRows(entradas).filter(e=>e.data&&e.data.slice(0,7)===m),dMes=activeRows(despesas).filter(d=>d.data&&d.data.slice(0,7)===m),by={};eHoje.forEach(e=>by[e.pagamento]=(by[e.pagamento]||0)+e.valor);dashReceitaHoje.textContent=money(sum(eHoje));dashDespesasHoje.textContent=money(sum(dHoje));dashLucroHoje.textContent=money(sum(eHoje)-sum(dHoje));dashReceitaMes.textContent=money(sum(eMes));dashLucroMes.textContent="Lucro estimado: "+money(sum(eMes)-sum(dMes));dashQtdEntradas.textContent=eHoje.length+" entradas";dashQtdDespesas.textContent=dHoje.length+" despesas";dashPix.textContent=money(by["PIX"]||0);dashCartao.textContent=money(by["Cartão"]||0);dashDinheiro.textContent=money(by["Dinheiro"]||0);let venc=contasVencendo().length;dashContasVencendo.textContent=venc;let pend=activeRows(entradas).filter(e=>e.nota==="Pendente").length;alertasDashboard.innerHTML=`<h3>Alertas</h3><p><span class="badge yellow">${pend} notas pendentes</span> <span class="badge ${venc?'red':'green'}">${venc} contas vencendo em 7 dias</span> <span class="badge ${closed(h)?'green':'blue'}">Dia ${closed(h)?'fechado':'aberto'}</span></p>`}
function renderEntradas(){let list=[...entradas].reverse(),q=filtroEntradaBusca.value.toLowerCase(),mes=filtroEntradaMes.value,st=filtroEntradaStatus.value;if(mes)list=list.filter(e=>e.data&&e.data.slice(0,7)===mes);if(st==="ativas")list=list.filter(e=>!e.cancelado);if(st==="canceladas")list=list.filter(e=>e.cancelado);if(q)list=list.filter(e=>[e.cliente,e.numeroNota,e.pagamento,e.usuario].join(" ").toLowerCase().includes(q));entradasTabela.innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Data</th><th>Cliente</th><th>Valor</th><th>Pagamento</th><th>Nota</th><th>Status</th><th>Ações</th></tr></thead><tbody>${list.map(e=>`<tr><td>${brDate(e.data)}</td><td>${escapeHTML(e.cliente)}<br><small>${escapeHTML(e.usuario)}</small></td><td>${money(e.valor)}</td><td>${escapeHTML(e.pagamento)}</td><td><b class="danger-text">Nº ${escapeHTML(e.numeroNota)}</b><br>${escapeHTML(e.nota)}</td><td>${e.cancelado?'<span class="badge red">Cancelada</span>':'<span class="badge green">Ativa</span>'}</td><td><button class="btn small" onclick="editarEntrada(${e.id})" ${e.cancelado?'disabled':''}>Editar</button> <button class="btn btn-danger small" onclick="cancelarEntrada(${e.id})" ${e.cancelado?'disabled':''}>Cancelar</button></td></tr>`).join("")}</tbody></table></div>`:"<p>Nenhuma entrada.</p>"}
function renderDespesas(){let list=[...despesas].reverse(),q=filtroDespesaBusca.value.toLowerCase(),mes=filtroDespesaMes.value,st=filtroDespesaStatus.value;if(mes)list=list.filter(d=>d.data&&d.data.slice(0,7)===mes);if(st==="ativas")list=list.filter(d=>!d.cancelado);if(st==="canceladas")list=list.filter(d=>d.cancelado);if(st==="pendentes")list=list.filter(d=>!d.cancelado&&d.status==="Pendente");if(q)list=list.filter(d=>[d.categoria,d.descricao,d.status,d.usuario].join(" ").toLowerCase().includes(q));despesasTabela.innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Data</th><th>Categoria</th><th>Descrição</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody>${list.map(d=>`<tr><td>${brDate(d.data)}</td><td>${escapeHTML(d.categoria)}<br><small>${escapeHTML(d.usuario)}</small></td><td>${escapeHTML(d.descricao)}</td><td>${money(d.valor)}</td><td>${d.cancelado?'<span class="badge red">Cancelada</span>':`<span class="badge ${d.status==='Pago'?'green':'yellow'}">${d.status}</span>`}</td><td><button class="btn small" onclick="editarDespesa(${d.id})" ${d.cancelado?'disabled':''}>Editar</button> <button class="btn btn-danger small" onclick="cancelarDespesa(${d.id})" ${d.cancelado?'disabled':''}>Cancelar</button></td></tr>`).join("")}</tbody></table></div>`:"<p>Nenhuma despesa.</p>"}
function renderNotas(){let list=activeRows(entradas),q=filtroNotasBusca.value.toLowerCase(),st=filtroNotasStatus.value;if(st==="pendentes")list=list.filter(e=>e.nota==="Pendente");if(st==="emitidas")list=list.filter(e=>e.nota==="Emitida");if(q)list=list.filter(e=>[e.numeroNota,e.cliente].join(" ").toLowerCase().includes(q));notasTabela.innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Nº Nota</th><th>Cliente</th><th>Valor</th><th>Status</th><th>Ação</th></tr></thead><tbody>${list.map(e=>`<tr><td><b class="danger-text">${escapeHTML(e.numeroNota)}</b></td><td>${escapeHTML(e.cliente)}</td><td>${money(e.valor)}</td><td><span class="badge ${e.nota==='Emitida'?'green':e.nota==='Pendente'?'yellow':'blue'}">${escapeHTML(e.nota)}</span></td><td>${e.nota==='Pendente'?`<button class="btn btn-success small" onclick="marcarNotaEmitida(${e.id})">Marcar emitida</button>`:""}</td></tr>`).join("")}</tbody></table></div>`:"<p>Nenhuma nota encontrada.</p>"}
function marcarNotaEmitida(id){let e=entradas.find(x=>x.id===id);if(!e)return;e.nota="Emitida";save(KEYS.entradas,entradas);audit("Marcou nota como emitida",`Nota ${e.numeroNota} - ${e.cliente}`);renderAll()}
function contasVencendo(){const t=new Date(today()+"T00:00:00"),lim=new Date(t);lim.setDate(lim.getDate()+7);return contas.filter(c=>!c.cancelado&&c.status==="Pendente"&&c.vencimento&&new Date(c.vencimento+"T00:00:00")<=lim)}
function renderContas(){let list=[...contas].reverse();contasTabela.innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Conta</th><th>Categoria</th><th>Valor</th><th>Vencimento</th><th>Status</th><th>Ação</th></tr></thead><tbody>${list.map(c=>`<tr><td>${escapeHTML(c.fornecedor)}<br><small>${escapeHTML(c.obs||"")}</small></td><td>${escapeHTML(c.categoria)}</td><td>${money(c.valor)}</td><td>${brDate(c.vencimento)}</td><td><span class="badge ${c.status==='Pago'?'green':'yellow'}">${c.status}</span></td><td>${c.status==="Pendente"?`<button class="btn btn-success small" onclick="marcarContaPaga(${c.id})">Marcar paga</button>`:""}</td></tr>`).join("")}</tbody></table></div>`:"<p>Nenhuma conta cadastrada.</p>"}
function renderFechamento(){const data=fechamentoData.value||today(),e=activeRows(entradas).filter(x=>x.data===data),d=activeRows(despesas).filter(x=>x.data===data),by={};e.forEach(x=>by[x.pagamento]=(by[x.pagamento]||0)+x.valor);fechamentoResumo.innerHTML=`<div class="cards"><div class="card"><span>Faturamento</span><strong>${money(sum(e))}</strong></div><div class="card"><span>Despesas</span><strong>${money(sum(d))}</strong></div><div class="card"><span>Lucro</span><strong>${money(sum(e)-sum(d))}</strong></div><div class="card"><span>Status</span><strong>${closed(data)?"Fechado":"Aberto"}</strong></div></div><div class="panel"><p><b>PIX:</b> ${money(by["PIX"]||0)} | <b>Cartão:</b> ${money(by["Cartão"]||0)} | <b>Dinheiro:</b> ${money(by["Dinheiro"]||0)} | <b>Transferência:</b> ${money(by["Transferência"]||0)}</p></div>`}
function fecharDia(){const data=fechamentoData.value||today();fechamentos[data]={usuario:fechamentoUsuario.value,fechadoEm:new Date().toLocaleString("pt-BR"),obs:fechamentoObs.value};save(KEYS.fechamentos,fechamentos);audit("Fechou dia",`${brDate(data)} por ${fechamentoUsuario.value}`);renderAll();alert("Dia fechado.")}
function gerarRelatorio(){const ini=relInicio.value||today(),fim=relFim.value||today(),pag=relPagamento.value,usu=relUsuario.value;let e=activeRows(entradas).filter(x=>x.data>=ini&&x.data<=fim),d=activeRows(despesas).filter(x=>x.data>=ini&&x.data<=fim);if(pag)e=e.filter(x=>x.pagamento===pag);if(usu){e=e.filter(x=>x.usuario===usu);d=d.filter(x=>x.usuario===usu)}relatorioConteudo.innerHTML=`<div class="cards"><div class="card"><span>Faturamento</span><strong>${money(sum(e))}</strong></div><div class="card"><span>Despesas</span><strong>${money(sum(d))}</strong></div><div class="card"><span>Lucro</span><strong>${money(sum(e)-sum(d))}</strong></div><div class="card"><span>Entradas</span><strong>${e.length}</strong></div></div>`}
function renderHistorico(){historicoTabela.innerHTML=auditoria.length?`<div class="table-wrap"><table><thead><tr><th>Data</th><th>Usuário</th><th>Ação</th><th>Detalhes</th></tr></thead><tbody>${auditoria.map(a=>`<tr><td>${escapeHTML(a.data)}</td><td>${escapeHTML(a.usuario)}</td><td>${escapeHTML(a.acao)}</td><td>${escapeHTML(a.detalhes)}</td></tr>`).join("")}</tbody></table></div>`:"<p>Nenhum histórico.</p>"}
function exportCSV(tipo){let rows=tipo==="entradas"?[["Data","Cliente","Valor","Pagamento","Nota","Numero Nota","Usuario"],...activeRows(entradas).map(e=>[brDate(e.data),e.cliente,e.valor,e.pagamento,e.nota,e.numeroNota,e.usuario])]:[["Data","Categoria","Descrição","Valor","Status","Usuario"],...activeRows(despesas).map(d=>[brDate(d.data),d.categoria,d.descricao,d.valor,d.status,d.usuario])];download(rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(";")).join("\n"),`${tipo}.csv`,"text/csv;charset=utf-8")}
function baixarBackup(){const data={config,entradas,despesas,contas,auditoria,fechamentos};download(JSON.stringify(data,null,2),"backup_erp_lavanderia_fatima.json","application/json");audit("Gerou backup","Backup baixado.")}
function importarBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);config=d.config||config;entradas=d.entradas||[];despesas=d.despesas||[];contas=d.contas||[];auditoria=d.auditoria||[];fechamentos=d.fechamentos||{};saveAll();renderAll();alert("Backup importado.")}catch(err){alert("Arquivo inválido.")}};r.readAsText(f)}
function limparDados(){if(prompt("Digite LIMPAR para apagar dados de teste")!=="LIMPAR")return;entradas=[];despesas=[];contas=[];auditoria=[];fechamentos={};saveAll();renderAll()}
function saveAll(){save(KEYS.config,config);save(KEYS.entradas,entradas);save(KEYS.despesas,despesas);save(KEYS.contas,contas);save(KEYS.auditoria,auditoria);save(KEYS.fechamentos,fechamentos)}
function download(content,name,type){const b=new Blob([content],{type});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function fillConfig(){cfgEmpresa.value=config.empresa;cfgTelefone.value=config.telefone;cfgEndereco.value=config.endereco;cfgSocia1.value=config.socias[0];cfgSocia2.value=config.socias[1];cfgSocia3.value=config.socias[2];cfgSenha.value=config.senha}
function salvarConfig(){config.empresa=cfgEmpresa.value||"Lavanderia Fátima";config.telefone=cfgTelefone.value;config.endereco=cfgEndereco.value;config.socias=[cfgSocia1.value||"Sócia 1",cfgSocia2.value||"Sócia 2",cfgSocia3.value||"Sócia 3"];config.senha=cfgSenha.value||"fatima2026";save(KEYS.config,config);fillUserSelects();alert("Configurações salvas.")}
